# 日本語のコメントを許可する
Style/AsciiComments:
  Enabled: false

Style/Encoding:
  Enabled: false

Style/VariableInterpolation:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/UnlessElse:
  Enabled: false

Layout/SpaceBeforeBlockBraces:
  Enabled: false

Layout/SpaceInsideParens:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Naming/VariableName:
  Enabled: false

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Layout/EmptyLineAfterMagicComment:
  Enabled: false

Layout/SpaceInsideBlockBraces:
  Enabled: false

# 正規表現の$1, $2はRegexp.last_match[n]を推奨
Style/PerlBackrefs:
  Enabled: false

# 空行
Layout/EmptyLines:
  Enabled: false

# メソッドパラメータにハッシュ{ ... }がついてて余計
Style/BracesAroundHashParameters:
  Enabled: false

# 不要なホワイトスペース
Layout/TrailingWhitespace:
  Enabled: false

# if分の中身が一行の場合は後置if文を使用するか、&& or ||リテラルを使用し、処理をコントロールして下さい
Style/IfUnlessModifier:
  Enabled: false

# 最後の評価だからreturn外してfalseにしても同じ挙動する
Style/RedundantReturn:
  Enabled: false

Style/CommentedKeyword:
  Enabled: false

# class endの前に無駄な改行
Layout/EmptyLinesAroundClassBody:
  Enabled: false

# ファイルの末尾に余分な空行がある
Layout/TrailingBlankLines:
  Enabled: false

# メソッド名のprefixに「set_」「get_」を使用してはいけない
AccessorMethodName:
  Enabled: false

Layout/LeadingCommentSpace:
  Enabled: false

# ブロックの本体の周りの空白行が設定と一致するか
Layout/EmptyLinesAroundBlockBody:
  Enabled: false

# ブロック内行数を25行以内におさめる
Metrics/BlockLength:
  Enabled: false

# デフォルトパラメータの=まわりにスペースがある
Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: false

# 余分なスペース
Layout/ExtraSpacing:
  Enabled: false

### rails ###
Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Layout/CommentIndentation:
  Enabled: false
